---
title: "flight delay"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{flight delay}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(BonusLab)
library(nycflights13)
library(dplyr)
library(caret)
library(knitr)
```

```{r}
data(weather)
data(flights)
```

```{r}
# data with weather
dww <- left_join(flights, weather, by=c("time_hour"="time_hour", "origin"="origin")) %>%
 select(dep_delay, origin, temp, wind_speed, precip, pressure, visib) %>%
 stats::na.omit() %>% mutate(wind_pre = wind_speed*precip,
                             wind_vis = wind_speed*visib)
```

```{r}
# row in data: 100%
rows_in_data <- 1:nrow(dww)

# test or validation: 100%*0.2 = 20%
test_val_Index <- caret::createDataPartition(rows_in_data, p = .2, 
                                  list = FALSE, 
                                  times = 1)
# Train: 100%-20% = 80%
train_index <- rows_in_data[-test_val_Index]

# validation: 0.75*20% = 15%
val_index <- caret::createDataPartition(test_val_Index, p = .75, 
                                  list = FALSE, 
                                  times = 1)

# test: 0.25*20% = 5%
test_index <- test_val_Index[-val_index]

data.frame(val=length(val_index)/length(rows_in_data),
           train=length(train_index)/length(rows_in_data),
           test=length(test_index)/length(rows_in_data))
```

```{r}
train_data <- as.data.frame(dww[train_index,])
val_data <- as.data.frame(dww[val_index,])
test_data <- as.data.frame(dww[test_index,])
```


```{r}
model1 <- ridgereg(data=train_data, formula=dep_delay~origin+temp+wind_speed+precip+pressure+visib+wind_pre+wind_vis, lambda=0)
#print(model1)
```

```{r}
model1$predict(val_data)
```

```{r}
RMSE_flight_delay <- function(model, validation=TRUE){
  if(validation==FALSE){
    data <- test_data
  } else if (validation==TRUE){
    data <- val_data
  }
  
  actual <- data$dep_delay
  pred <- model$predict(data)
  
  return(sqrt(sum((pred-actual)^2/length(actual))))
}
```

```{r}
# RMSE on validation data
RMSE_flight_delay(model1, validation=TRUE)
```
```{r}
model1 <- ridgereg(data=train_data, formula=dep_delay~origin+temp+wind_speed+precip+pressure+visib+wind_pre+wind_vis, lambda=1)
model2 <- ridgereg(data=train_data, formula=dep_delay~origin+temp+wind_speed+precip+pressure+visib+wind_pre+wind_vis, lambda=5)
model3 <- ridgereg(data=train_data, formula=dep_delay~origin+temp+wind_speed+precip+pressure+visib+wind_pre+wind_vis, lambda=10)
model4 <- ridgereg(data=train_data, formula=dep_delay~origin+temp+wind_speed+precip+pressure+visib+wind_pre+wind_vis, lambda=25)
model5 <- ridgereg(data=train_data, formula=dep_delay~origin+temp+wind_speed+precip+pressure+visib+wind_pre+wind_vis, lambda=50)
model6 <- ridgereg(data=train_data, formula=dep_delay~origin+temp+wind_speed+precip+pressure+visib+wind_pre+wind_vis, lambda=100)
model7 <- ridgereg(data=train_data, formula=dep_delay~origin+temp+wind_speed+precip+pressure+visib+wind_pre+wind_vis, lambda=200)
model8 <- ridgereg(data=train_data, formula=dep_delay~origin+temp+wind_speed+precip+pressure+visib+wind_pre+wind_vis, lambda=500)
model9 <- ridgereg(data=train_data, formula=dep_delay~origin+temp+wind_speed+precip+pressure+visib+wind_pre+wind_vis, lambda=1000)
RMSE1 <- RMSE_flight_delay(model1, validation=TRUE)
RMSE2 <- RMSE_flight_delay(model2, validation=TRUE)
RMSE3 <- RMSE_flight_delay(model3, validation=TRUE)
RMSE4 <- RMSE_flight_delay(model4, validation=TRUE)
RMSE5 <- RMSE_flight_delay(model5, validation=TRUE)
RMSE6 <- RMSE_flight_delay(model6, validation=TRUE)
RMSE7 <- RMSE_flight_delay(model7, validation=TRUE)
RMSE8 <- RMSE_flight_delay(model8, validation=TRUE)
RMSE9 <- RMSE_flight_delay(model9, validation=TRUE)
```


```{r}
RMSE_table <- data.frame(lambda=c(1,5,10,25,50,100,200,500,1000),
           `Validarion RMSE`=c(RMSE1, RMSE2, RMSE3, RMSE4, RMSE5, RMSE6, RMSE7, RMSE8, RMSE9))
```

```{r}
kable(RMSE_table)
```

